-- 입실론 v61: 모의고사 클라우드 저장 + 상담 전략 공개
create table if not exists public.mock_scores (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  exam_year smallint not null default 2027,
  exam_type text not null check (exam_type in ('6월 모평','7월 학평','9월 모평','수능')),
  score_data jsonb not null default '{}'::jsonb,
  wrong_items jsonb not null default '{}'::jsonb,
  source_mode text not null default 'estimated' check (source_mode in ('estimated','wrong_items','external','official')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(student_id, exam_year, exam_type)
);

create table if not exists public.consultation_plans (
  id bigint generated by default as identity primary key,
  student_id uuid not null unique references public.profiles(id) on delete cascade,
  counselor_id uuid references public.profiles(id) on delete set null,
  plan_data jsonb not null default '{}'::jsonb,
  counselor_note text not null default '',
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists mock_scores_student_idx on public.mock_scores(student_id, exam_year, exam_type);
create index if not exists consultation_plans_student_idx on public.consultation_plans(student_id);

alter table public.mock_scores enable row level security;
alter table public.consultation_plans enable row level security;

create or replace function public.is_counselor()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role::text in ('teacher','director'));
$$;
revoke all on function public.is_counselor() from public;
grant execute on function public.is_counselor() to authenticated;

drop policy if exists "mock scores own or staff read" on public.mock_scores;
create policy "mock scores own or staff read" on public.mock_scores for select to authenticated
using (student_id = auth.uid() or public.is_counselor());
drop policy if exists "mock scores own insert" on public.mock_scores;
create policy "mock scores own insert" on public.mock_scores for insert to authenticated
with check (student_id = auth.uid());
drop policy if exists "mock scores own update" on public.mock_scores;
create policy "mock scores own update" on public.mock_scores for update to authenticated
using (student_id = auth.uid()) with check (student_id = auth.uid());
drop policy if exists "mock scores own delete" on public.mock_scores;
create policy "mock scores own delete" on public.mock_scores for delete to authenticated
using (student_id = auth.uid());

drop policy if exists "consultation staff manage" on public.consultation_plans;
create policy "consultation staff manage" on public.consultation_plans for all to authenticated
using (public.is_counselor()) with check (public.is_counselor());
drop policy if exists "consultation student published read" on public.consultation_plans;
create policy "consultation student published read" on public.consultation_plans for select to authenticated
using (student_id = auth.uid() and published = true);

grant select,insert,update,delete on public.mock_scores to authenticated;
grant select,insert,update,delete on public.consultation_plans to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.touch_counseling_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists mock_scores_touch on public.mock_scores;
create trigger mock_scores_touch before update on public.mock_scores for each row execute function public.touch_counseling_updated_at();
drop trigger if exists consultation_plans_touch on public.consultation_plans;
create trigger consultation_plans_touch before update on public.consultation_plans for each row execute function public.touch_counseling_updated_at();
